ArquiteturaLimpaMVC.WebUI/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ArquiteturaLimpaMVC.WebUI.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "O email é obrigatório!")]
        [EmailAddress(ErrorMessage = "Formato Inválido do Email!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "A senha é obrigatória!")]
        [StringLength(20, MinimumLength = 10, ErrorMessage = "A {0} deve ter no mínimo {1} e no máximo {2} caracteres!")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        public string UrlRetorno { get; set; }
    }
}

ArquiteturaLimpaMVC.WebUI/Controllers/ContaController.cs
using ArquiteturaLimpaMVC.Dominio.Conta;
using ArquiteturaLimpaMVC.WebUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ArquiteturaLimpaMVC.WebUI.Controllers
{
    public class ContaController : Controller
    {
        private readonly IAuthenticate _authenticate;

        public ContaController(IAuthenticate authenticate)
        {
            _authenticate = authenticate;
        }

        [HttpGet]
        public IActionResult Login(string urlRetorno)
        {
            return View(new LoginViewModel()
            {
                UrlRetorno = urlRetorno
            });
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            var resultado = await _authenticate.Authenticate(loginViewModel.Email, loginViewModel.Senha);

            if (resultado)
            {
                if (string.IsNullOrEmpty(loginViewModel.UrlRetorno))
                {
                    return RedirectToAction("Index", "Home");
                }
                return Redirect(loginViewModel.UrlRetorno);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Login Inválido. A senha definida deve ser forte!");
                return View(loginViewModel);
            }
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registrar(RegistroViewModel registroViewModel)
        {
            var resultado = await _authenticate.RegistrarUsuario(registroViewModel.Email, registroViewModel.Senha);

            if (resultado)
            {
                return Redirect("/");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Login Inválido. A senha definida deve ser forte!");
                return View(registroViewModel);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Sair()
        {
            await _authenticate.Sair();
            return Redirect("/Conta/Login");
        }
    }
}

ArquiteturaLimpaMVC.WebUI/Views/Conta/Login.cshtml
@model LoginViewModel

<h2>LogIn:</h2>

<div class="row">
    <div class="col-md-10">

        <form asp-controller="Conta" asp-action="Login" method="post" class="form-horizontal">

            <input type="hidden" asp-for="UrlRetorno" />

            <div asp-validation-summary="All" class="text-danger">
            </div>

            <div class="form-group">
                <label asp-for="Email" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">

                <label asp-for="Senha" class="col-md-2 control-label"></label>

                <div class="col-md-10">
                    <input asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-outline-dark">Login</button>
                </div>
            </div>

            <p>
                <a asp-action="Registrar">Cadastrar um novo usuário?</a>
            </p>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ArquiteturaLimpaMVC.WebUI/Views/Conta/Registrar.cshtml
@model RegistroViewModel

<h3>Cadastrar Usuário</h3>

<div class="row">
    <div class="col-md-12">
        <form asp-controller="Conta" asp-action="Registrar" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmarSenha"></label>
                <input asp-for="ConfirmarSenha" class="form-control" />
                <span asp-validation-for="ConfirmarSenha" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-outline-dark">Registrar</button>
            <a asp-controller="Home" asp-action="Index" class="btn btn-link">Retornar</a>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}